version: '3.9'

services:

  house-pwa:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    image: ${CONTAINER_REGISTRY}/house-pwa:${TAG}
    container_name: house-pwa
    restart: always
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "8142:80"
    environment:
      - BUILD_NUMBER=${TAG}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.house-pwa.rule=Host(`house-pwa.docduck.io`)"
    networks:
      - printdown-network

networks:
  printdown-network:
    external: true